// https://www.nesdev.org/wiki/PPU_memory_map

// Pattern Tables

pub const PATTERN_TABLE_SIZE: u16 = 4096;

pub const PATTERN_TABLES_START_ADDR: u16 = 0x0000;

pub const PATTERN_TABLE_0_START_ADDR: u16 = PATTERN_TABLES_START_ADDR;
pub const PATTERN_TABLE_0_END_ADDR: u16 = PATTERN_TABLE_0_START_ADDR + PATTERN_TABLE_SIZE;

pub const PATTERN_TABLE_1_START_ADDR: u16 = PATTERN_TABLE_0_END_ADDR;
pub const PATTERN_TABLE_1_END_ADDR: u16 = PATTERN_TABLE_1_START_ADDR + PATTERN_TABLE_SIZE;

pub const PATTERN_TABLES_END_ADDR: u16 = PATTERN_TABLE_1_END_ADDR;

// Nametables & Attribute Tables

pub const NAMETABLE_SIZE: u16 = 960;
pub const NAMETABLE_COUNT: u16 = 4;
pub const ATTRIBUTE_TABLE_SIZE: u16 = 64;
pub const ATTRIBUTE_TABLE_COUNT: u16 = NAMETABLE_COUNT;

pub const NAMETABLES_START_ADDR: u16 = PATTERN_TABLES_END_ADDR;

pub const NAMETABLE_0_START_ADDR: u16 = NAMETABLES_START_ADDR;
pub const NAMETABLE_0_END_ADDR: u16 = NAMETABLE_0_START_ADDR + NAMETABLE_SIZE;
pub const ATTRIBUTE_TABLE_0_START_ADDR: u16 = NAMETABLE_0_END_ADDR;
pub const ATTRIBUTE_TABLE_0_END_ADDR: u16 = ATTRIBUTE_TABLE_0_START_ADDR + ATTRIBUTE_TABLE_SIZE;

pub const NAMETABLE_1_START_ADDR: u16 = ATTRIBUTE_TABLE_0_END_ADDR;
pub const NAMETABLE_1_END_ADDR: u16 = NAMETABLE_1_START_ADDR + NAMETABLE_SIZE;
pub const ATTRIBUTE_TABLE_1_START_ADDR: u16 = NAMETABLE_1_END_ADDR;
pub const ATTRIBUTE_TABLE_1_END_ADDR: u16 = ATTRIBUTE_TABLE_1_START_ADDR + ATTRIBUTE_TABLE_SIZE;

pub const NAMETABLE_2_START_ADDR: u16 = ATTRIBUTE_TABLE_1_END_ADDR;
pub const NAMETABLE_2_END_ADDR: u16 = NAMETABLE_2_START_ADDR + NAMETABLE_SIZE;
pub const ATTRIBUTE_TABLE_2_START_ADDR: u16 = NAMETABLE_2_END_ADDR;
pub const ATTRIBUTE_TABLE_2_END_ADDR: u16 = ATTRIBUTE_TABLE_2_START_ADDR + ATTRIBUTE_TABLE_SIZE;

pub const NAMETABLE_3_START_ADDR: u16 = ATTRIBUTE_TABLE_2_END_ADDR;
pub const NAMETABLE_3_END_ADDR: u16 = NAMETABLE_3_START_ADDR + NAMETABLE_SIZE;
pub const ATTRIBUTE_TABLE_3_START_ADDR: u16 = NAMETABLE_3_END_ADDR;
pub const ATTRIBUTE_TABLE_3_END_ADDR: u16 = ATTRIBUTE_TABLE_3_START_ADDR + ATTRIBUTE_TABLE_SIZE;

pub const NAMETABLES_END_ADDR: u16 = ATTRIBUTE_TABLE_3_END_ADDR;

// Unused

pub const UNUSED_SIZE: u16 = 3840;

pub const UNUSED_START_ADDR: u16 = NAMETABLES_END_ADDR;
pub const UNUSED_END_ADDR: u16 = UNUSED_START_ADDR + UNUSED_SIZE;

// Palette RAM

pub const PALETTE_SIZE: u16 = 4;
pub const PALETTE_COUNT: u16 = 8;
pub const PALETTE_RAM_SIZE: u16 = PALETTE_SIZE * PALETTE_COUNT;
pub const PALETTE_RAM_MIRRORS_SIZE: u16 = 224;

pub const PALETTE_RAM_START_ADDR: u16 = UNUSED_END_ADDR;

pub const PALETTE_RAM_BACKGROUND_START_ADDR: u16 = PALETTE_RAM_START_ADDR;
pub const PALETTE_RAM_BACKGROUND_END_ADDR: u16 =
    PALETTE_RAM_BACKGROUND_START_ADDR + (PALETTE_RAM_SIZE / 2);

pub const PALETTE_RAM_SPRITE_START_ADDR: u16 = PALETTE_RAM_BACKGROUND_END_ADDR;
pub const PALETTE_RAM_SPITE_END_ADDR: u16 = PALETTE_RAM_SPRITE_START_ADDR + (PALETTE_RAM_SIZE / 2);

pub const PALETTE_RAM_MIRRORS_START_ADDR: u16 = PALETTE_RAM_SPITE_END_ADDR;
pub const PALETTE_RAM_MIRRORS_END_ADDR: u16 =
    PALETTE_RAM_MIRRORS_START_ADDR + PALETTE_RAM_MIRRORS_SIZE;

pub const PALETTE_RAM_END_ADDR: u16 = PALETTE_RAM_MIRRORS_END_ADDR;
